# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-28 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='reliese_date',
            new_name='release_date',
        ),
    ]
